import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUserFromRequest } from "@/lib/auth";
import { hasPermission } from "@/lib/permissions";
import { processAutomations } from "@/lib/automations";
import { eventHub } from "@/lib/events";

export async function POST(request: NextRequest) {
  try {
    const currentUser = await getCurrentUserFromRequest(request);
    if (!currentUser || !hasPermission(currentUser.role, "task.create")) {
      return NextResponse.json(
        { success: false, error: { code: "FORBIDDEN", message: "You lack permission to create tasks" } },
        { status: 403 }
      );
    }

    const { actionType, details } = await request.json();

    if (actionType === "CREATE_TASK") {
      let projectId = details.projectId;
      if (!projectId) {
        const p = await prisma.project.findFirst({ where: { status: "ACTIVE" } });
        projectId = p?.id;
      }

      const project = await prisma.project.findUnique({
        where: { id: projectId },
      });

      if (!project) {
        return NextResponse.json({ success: false, error: { code: "NOT_FOUND", message: "Project not found" } }, { status: 404 });
      }

      const taskCount = await prisma.task.count({ where: { projectId } });
      const taskKey = `${project.key}-${100 + taskCount + 1}`;

      const task = await prisma.task.create({
        data: {
          taskKey,
          title: details.title,
          description: details.description || `Generated via DX AI Assistant by ${currentUser.name}`,
          projectId,
          taskType: details.taskType || "TASK",
          status: details.status || "TODO",
          priority: details.priority || "MEDIUM",
          reporterId: currentUser.id,
          dueDate: details.dueDate ? new Date(details.dueDate) : null,
          position: taskCount,
          assignees: details.assigneeId
            ? { create: [{ userId: details.assigneeId }] }
            : undefined,
        },
        include: {
          project: true,
          assignees: { include: { user: true } },
        },
      });

      // Audit Log
      await prisma.auditLog.create({
        data: {
          userId: currentUser.id,
          action: "AI_ACTION_EXECUTED",
          entityType: "TASK",
          entityId: task.id,
          detailsJson: JSON.stringify({ actionType, taskKey: task.taskKey, title: task.title }),
        },
      });

      // Activity
      await prisma.activity.create({
        data: {
          taskId: task.id,
          projectId: task.projectId,
          userId: currentUser.id,
          action: "CREATED",
          description: `${currentUser.name} created ${task.taskKey} via DX AI Action`,
        },
      });

      if (details.assigneeId) {
        await processAutomations({
          triggerType: "TASK_ASSIGNED",
          taskId: task.id,
          projectId: task.projectId,
          metadata: {
            assigneeId: details.assigneeId,
            assignerName: currentUser.name,
          },
        });
      }

      eventHub.emit("task_created", { taskKey: task.taskKey, projectId: task.projectId });

      return NextResponse.json({
        success: true,
        data: task,
        message: `Task ${task.taskKey} created successfully via DX AI!`,
      });
    }

    if (actionType === "BREAKDOWN_PLAN") {
      let projectId = details.projectId;
      if (!projectId) {
        const p = await prisma.project.findFirst({ where: { status: "ACTIVE" } });
        projectId = p?.id;
      }

      const project = await prisma.project.findUnique({
        where: { id: projectId },
      });

      if (!project) {
        return NextResponse.json({ success: false, error: { code: "NOT_FOUND", message: "Project not found" } }, { status: 404 });
      }

      const taskCount = await prisma.task.count({ where: { projectId } });
      const parentTaskKey = `${project.key}-${100 + taskCount + 1}`;

      // Create Parent Task
      const parentTask = await prisma.task.create({
        data: {
          taskKey: parentTaskKey,
          title: details.parentTitle,
          description: `Feature Breakdown parent task generated by DX AI with ${details.subtasks?.length || 0} subtasks.`,
          projectId,
          taskType: "FEATURE",
          status: "TODO",
          priority: details.priority || "HIGH",
          reporterId: currentUser.id,
          position: taskCount,
          subtasks: {
            create: (details.subtasks || []).map((subTitle: string) => ({
              title: subTitle,
              completed: false,
            })),
          },
        },
        include: {
          subtasks: true,
        },
      });

      // Audit Log
      await prisma.auditLog.create({
        data: {
          userId: currentUser.id,
          action: "AI_ACTION_EXECUTED",
          entityType: "TASK",
          entityId: parentTask.id,
          detailsJson: JSON.stringify({ actionType: "BREAKDOWN_PLAN", parentTaskKey, subtasks: details.subtasks }),
        },
      });

      // Activity
      await prisma.activity.create({
        data: {
          taskId: parentTask.id,
          projectId: parentTask.projectId,
          userId: currentUser.id,
          action: "CREATED",
          description: `${currentUser.name} created requirement breakdown ${parentTask.taskKey} with ${details.subtasks?.length} subtasks via DX AI`,
        },
      });

      eventHub.emit("task_created", { taskKey: parentTask.taskKey, projectId: parentTask.projectId });

      return NextResponse.json({
        success: true,
        data: parentTask,
        message: `Created parent feature ${parentTask.taskKey} with ${details.subtasks?.length} subtasks!`,
      });
    }

    return NextResponse.json({ success: false, error: { code: "UNSUPPORTED_ACTION", message: "Action type not supported" } }, { status: 400 });
  } catch (error: any) {
    console.error("Execute AI action error:", error);
    return NextResponse.json({ success: false, error: { code: "SERVER_ERROR", message: "Failed to execute confirmed AI action" } }, { status: 500 });
  }
}
